// Database types - generated from Supabase schema

export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          email: string;
          username: string | null;
          first_name: string;
          last_name: string;
          phone: string | null;
          date_of_birth: string | null;
          avatar_url: string | null;
          bio: string | null;
          role: 'traveler' | 'host' | 'both' | 'admin';
          status: 'active' | 'suspended' | 'pending_verification';
          verification_status: 'unverified' | 'pending' | 'verified' | 'rejected';
          verification_documents: any | null;
          languages: string[] | null;
          location: any | null;
          preferences: any | null;
          social_links: any | null;
          revenue_cat_id: string | null;
          stream_user_token: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          username?: string | null;
          first_name: string;
          last_name: string;
          phone?: string | null;
          date_of_birth?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          role?: 'traveler' | 'host' | 'both' | 'admin';
          status?: 'active' | 'suspended' | 'pending_verification';
          verification_status?: 'unverified' | 'pending' | 'verified' | 'rejected';
          verification_documents?: any | null;
          languages?: string[] | null;
          location?: any | null;
          preferences?: any | null;
          social_links?: any | null;
          revenue_cat_id?: string | null;
          stream_user_token?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          username?: string | null;
          first_name?: string;
          last_name?: string;
          phone?: string | null;
          date_of_birth?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          role?: 'traveler' | 'host' | 'both' | 'admin';
          status?: 'active' | 'suspended' | 'pending_verification';
          verification_status?: 'unverified' | 'pending' | 'verified' | 'rejected';
          verification_documents?: any | null;
          languages?: string[] | null;
          location?: any | null;
          preferences?: any | null;
          social_links?: any | null;
          revenue_cat_id?: string | null;
          stream_user_token?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      listings: {
        Row: {
          id: string;
          host_id: string;
          title: string;
          description: string;
          listing_type: 'accommodation' | 'experience' | 'service';
          property_type: 'house' | 'apartment' | 'villa' | 'cabin' | 'hotel_room' | 'unique' | null;
          category: string | null;
          address: any;
          coordinates: any;
          base_price: number;
          currency: string;
          price_per: string;
          cleaning_fee: number;
          service_fee: number;
          max_guests: number;
          min_nights: number;
          max_nights: number | null;
          instant_book: boolean;
          amenities: string[];
          features: any;
          house_rules: string[];
          available_from: string | null;
          available_to: string | null;
          blocked_dates: string[];
          images: any;
          video_url: string | null;
          virtual_tour_url: string | null;
          status: 'draft' | 'active' | 'inactive' | 'suspended';
          views: number;
          average_rating: number;
          review_count: number;
          featured: boolean;
          verified: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          host_id: string;
          title: string;
          description: string;
          listing_type: 'accommodation' | 'experience' | 'service';
          property_type?: 'house' | 'apartment' | 'villa' | 'cabin' | 'hotel_room' | 'unique' | null;
          category?: string | null;
          address: any;
          coordinates: any;
          base_price: number;
          currency?: string;
          price_per?: string;
          cleaning_fee?: number;
          service_fee?: number;
          max_guests?: number;
          min_nights?: number;
          max_nights?: number | null;
          instant_book?: boolean;
          amenities?: string[];
          features?: any;
          house_rules?: string[];
          available_from?: string | null;
          available_to?: string | null;
          blocked_dates?: string[];
          images: any;
          video_url?: string | null;
          virtual_tour_url?: string | null;
          status?: 'draft' | 'active' | 'inactive' | 'suspended';
          views?: number;
          average_rating?: number;
          review_count?: number;
          featured?: boolean;
          verified?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          host_id?: string;
          title?: string;
          description?: string;
          listing_type?: 'accommodation' | 'experience' | 'service';
          property_type?: 'house' | 'apartment' | 'villa' | 'cabin' | 'hotel_room' | 'unique' | null;
          category?: string | null;
          address?: any;
          coordinates?: any;
          base_price?: number;
          currency?: string;
          price_per?: string;
          cleaning_fee?: number;
          service_fee?: number;
          max_guests?: number;
          min_nights?: number;
          max_nights?: number | null;
          instant_book?: boolean;
          amenities?: string[];
          features?: any;
          house_rules?: string[];
          available_from?: string | null;
          available_to?: string | null;
          blocked_dates?: string[];
          images?: any;
          video_url?: string | null;
          virtual_tour_url?: string | null;
          status?: 'draft' | 'active' | 'inactive' | 'suspended';
          views?: number;
          average_rating?: number;
          review_count?: number;
          featured?: boolean;
          verified?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      bookings: {
        Row: {
          id: string;
          listing_id: string;
          guest_id: string;
          host_id: string;
          check_in: string;
          check_out: string;
          guests: number;
          nights: number;
          base_amount: number;
          cleaning_fee: number;
          service_fee: number;
          taxes: number;
          total_amount: number;
          currency: string;
          payment_status: 'pending' | 'paid' | 'failed' | 'refunded' | 'partially_refunded';
          payment_intent_id: string | null;
          paid_amount: number;
          refunded_amount: number;
          status: 'pending' | 'confirmed' | 'cancelled' | 'completed' | 'refunded';
          cancellation_reason: string | null;
          cancelled_by: string | null;
          cancelled_at: string | null;
          special_requests: string | null;
          host_notes: string | null;
          guest_notes: string | null;
          booking_code: string;
          escrow_id: string | null;
          check_in_id: string | null;
          payout_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          listing_id: string;
          guest_id: string;
          host_id: string;
          check_in: string;
          check_out: string;
          guests: number;
          nights: number;
          base_amount: number;
          cleaning_fee?: number;
          service_fee?: number;
          taxes?: number;
          total_amount: number;
          currency?: string;
          payment_status?: 'pending' | 'paid' | 'failed' | 'refunded' | 'partially_refunded';
          payment_intent_id?: string | null;
          paid_amount?: number;
          refunded_amount?: number;
          status?: 'pending' | 'confirmed' | 'cancelled' | 'completed' | 'refunded';
          cancellation_reason?: string | null;
          cancelled_by?: string | null;
          cancelled_at?: string | null;
          special_requests?: string | null;
          host_notes?: string | null;
          guest_notes?: string | null;
          booking_code?: string;
          escrow_id?: string | null;
          check_in_id?: string | null;
          payout_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          listing_id?: string;
          guest_id?: string;
          host_id?: string;
          check_in?: string;
          check_out?: string;
          guests?: number;
          nights?: number;
          base_amount?: number;
          cleaning_fee?: number;
          service_fee?: number;
          taxes?: number;
          total_amount?: number;
          currency?: string;
          payment_status?: 'pending' | 'paid' | 'failed' | 'refunded' | 'partially_refunded';
          payment_intent_id?: string | null;
          paid_amount?: number;
          refunded_amount?: number;
          status?: 'pending' | 'confirmed' | 'cancelled' | 'completed' | 'refunded';
          cancellation_reason?: string | null;
          cancelled_by?: string | null;
          cancelled_at?: string | null;
          special_requests?: string | null;
          host_notes?: string | null;
          guest_notes?: string | null;
          booking_code?: string;
          escrow_id?: string | null;
          check_in_id?: string | null;
          payout_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      payments: {
        Row: {
          id: string;
          booking_id: string;
          stripe_payment_intent_id: string;
          amount: number;
          currency: string;
          platform_fee: number;
          host_amount: number;
          status: 'pending' | 'succeeded' | 'failed' | 'canceled';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          stripe_payment_intent_id: string;
          amount: number;
          currency?: string;
          platform_fee: number;
          host_amount: number;
          status?: 'pending' | 'succeeded' | 'failed' | 'canceled';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          stripe_payment_intent_id?: string;
          amount?: number;
          currency?: string;
          platform_fee?: number;
          host_amount?: number;
          status?: 'pending' | 'succeeded' | 'failed' | 'canceled';
          created_at?: string;
          updated_at?: string;
        };
      };
      escrow: {
        Row: {
          id: string;
          booking_id: string;
          status: 'held' | 'released' | 'disputed';
          held_amount: number;
          released_amount: number;
          release_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          status?: 'held' | 'released' | 'disputed';
          held_amount: number;
          released_amount?: number;
          release_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          status?: 'held' | 'released' | 'disputed';
          held_amount?: number;
          released_amount?: number;
          release_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      check_ins: {
        Row: {
          id: string;
          booking_id: string;
          checked_in_at: string;
          checked_in_by: string;
          method: 'self' | 'host' | 'code';
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          checked_in_at: string;
          checked_in_by: string;
          method?: 'self' | 'host' | 'code';
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          checked_in_at?: string;
          checked_in_by?: string;
          method?: 'self' | 'host' | 'code';
          notes?: string | null;
          created_at?: string;
        };
      };
      payouts: {
        Row: {
          id: string;
          booking_id: string;
          host_id: string;
          amount: number;
          currency: string;
          stripe_transfer_id: string | null;
          status: 'pending' | 'paid' | 'failed';
          scheduled_at: string | null;
          paid_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          host_id: string;
          amount: number;
          currency?: string;
          stripe_transfer_id?: string | null;
          status?: 'pending' | 'paid' | 'failed';
          scheduled_at?: string | null;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          host_id?: string;
          amount?: number;
          currency?: string;
          stripe_transfer_id?: string | null;
          status?: 'pending' | 'paid' | 'failed';
          scheduled_at?: string | null;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      reviews: {
        Row: {
          id: string;
          booking_id: string;
          listing_id: string;
          reviewer_id: string;
          reviewee_id: string;
          rating: number;
          title: string | null;
          comment: string | null;
          cleanliness_rating: number | null;
          communication_rating: number | null;
          location_rating: number | null;
          value_rating: number | null;
          is_public: boolean;
          is_verified: boolean;
          host_response: string | null;
          host_responded_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          listing_id: string;
          reviewer_id: string;
          reviewee_id: string;
          rating: number;
          title?: string | null;
          comment?: string | null;
          cleanliness_rating?: number | null;
          communication_rating?: number | null;
          location_rating?: number | null;
          value_rating?: number | null;
          is_public?: boolean;
          is_verified?: boolean;
          host_response?: string | null;
          host_responded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          listing_id?: string;
          reviewer_id?: string;
          reviewee_id?: string;
          rating?: number;
          title?: string | null;
          comment?: string | null;
          cleanliness_rating?: number | null;
          communication_rating?: number | null;
          location_rating?: number | null;
          value_rating?: number | null;
          is_public?: boolean;
          is_verified?: boolean;
          host_response?: string | null;
          host_responded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      message_threads: {
        Row: {
          id: string;
          booking_id: string | null;
          listing_id: string | null;
          participants: string[];
          stream_channel_id: string;
          stream_channel_type: string;
          last_message_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          booking_id?: string | null;
          listing_id?: string | null;
          participants: string[];
          stream_channel_id: string;
          stream_channel_type?: string;
          last_message_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string | null;
          listing_id?: string | null;
          participants?: string[];
          stream_channel_id?: string;
          stream_channel_type?: string;
          last_message_at?: string | null;
          created_at?: string;
        };
      };
      social_posts: {
        Row: {
          id: string;
          author_id: string;
          content: string | null;
          post_type: 'text' | 'image' | 'video' | 'listing_share' | 'trip_update';
          media_urls: any | null;
          listing_id: string | null;
          booking_id: string | null;
          location: any | null;
          likes_count: number;
          comments_count: number;
          shares_count: number;
          stream_activity_id: string | null;
          status: 'draft' | 'published' | 'archived' | 'reported';
          visibility: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          author_id: string;
          content?: string | null;
          post_type?: 'text' | 'image' | 'video' | 'listing_share' | 'trip_update';
          media_urls?: any | null;
          listing_id?: string | null;
          booking_id?: string | null;
          location?: any | null;
          likes_count?: number;
          comments_count?: number;
          shares_count?: number;
          stream_activity_id?: string | null;
          status?: 'draft' | 'published' | 'archived' | 'reported';
          visibility?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          author_id?: string;
          content?: string | null;
          post_type?: 'text' | 'image' | 'video' | 'listing_share' | 'trip_update';
          media_urls?: any | null;
          listing_id?: string | null;
          booking_id?: string | null;
          location?: any | null;
          likes_count?: number;
          comments_count?: number;
          shares_count?: number;
          stream_activity_id?: string | null;
          status?: 'draft' | 'published' | 'archived' | 'reported';
          visibility?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          revenue_cat_subscription_id: string;
          product_id: string;
          tier: 'basic' | 'premium' | 'host_pro' | 'enterprise';
          status: 'active' | 'cancelled' | 'expired' | 'trial' | 'paused';
          starts_at: string;
          expires_at: string | null;
          price: number;
          currency: string;
          billing_period: string | null;
          features: any | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          revenue_cat_subscription_id: string;
          product_id: string;
          tier: 'basic' | 'premium' | 'host_pro' | 'enterprise';
          status: 'active' | 'cancelled' | 'expired' | 'trial' | 'paused';
          starts_at: string;
          expires_at?: string | null;
          price: number;
          currency?: string;
          billing_period?: string | null;
          features?: any | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          revenue_cat_subscription_id?: string;
          product_id?: string;
          tier?: 'basic' | 'premium' | 'host_pro' | 'enterprise';
          status?: 'active' | 'cancelled' | 'expired' | 'trial' | 'paused';
          starts_at?: string;
          expires_at?: string | null;
          price?: number;
          currency?: string;
          billing_period?: string | null;
          features?: any | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      amenities: {
        Row: {
          id: string;
          name: string;
          category: string;
          icon: string | null;
          description: string | null;
          listing_types: string[];
        };
        Insert: {
          id: string;
          name: string;
          category: string;
          icon?: string | null;
          description?: string | null;
          listing_types?: string[];
        };
        Update: {
          id?: string;
          name?: string;
          category?: string;
          icon?: string | null;
          description?: string | null;
          listing_types?: string[];
        };
      };
      user_favorites: {
        Row: {
          id: string;
          user_id: string;
          listing_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          listing_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          listing_id?: string;
          created_at?: string;
        };
      };
      search_history: {
        Row: {
          id: string;
          user_id: string | null;
          session_id: string | null;
          query: string | null;
          location: string | null;
          check_in: string | null;
          check_out: string | null;
          guests: number | null;
          filters: any | null;
          results_count: number;
          clicked_listings: string[];
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          session_id?: string | null;
          query?: string | null;
          location?: string | null;
          check_in?: string | null;
          check_out?: string | null;
          guests?: number | null;
          filters?: any | null;
          results_count?: number;
          clicked_listings?: string[];
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          session_id?: string | null;
          query?: string | null;
          location?: string | null;
          check_in?: string | null;
          check_out?: string | null;
          guests?: number | null;
          filters?: any | null;
          results_count?: number;
          clicked_listings?: string[];
          created_at?: string;
        };
      };
    };
  };
}

export type UserProfile = Database['public']['Tables']['user_profiles']['Row'];
export type Listing = Database['public']['Tables']['listings']['Row'];
export type Booking = Database['public']['Tables']['bookings']['Row'];
export type Payment = Database['public']['Tables']['payments']['Row'];
export type Escrow = Database['public']['Tables']['escrow']['Row'];
export type CheckIn = Database['public']['Tables']['check_ins']['Row'];
export type Payout = Database['public']['Tables']['payouts']['Row'];
export type Review = Database['public']['Tables']['reviews']['Row'];
export type MessageThread = Database['public']['Tables']['message_threads']['Row'];
export type SocialPost = Database['public']['Tables']['social_posts']['Row'];
export type Subscription = Database['public']['Tables']['subscriptions']['Row'];
export type Amenity = Database['public']['Tables']['amenities']['Row'];
export type UserFavorite = Database['public']['Tables']['user_favorites']['Row'];
export type SearchHistory = Database['public']['Tables']['search_history']['Row'];